def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    #config.add_route('home', '/')
    config.add_route('index','/')
    config.add_route('admin-link','/admin-link')
    config.add_route('admin-professors','/admin-professors')
    config.add_route('admin-snapshot','/admin-snapshot')
    config.add_route('admin-students','/admin-students')
    config.add_route('index-get-started','/index-get-started')
    config.add_route('index-sign-in','/index-sign-in')
    config.add_route('professor-chapters','/professor-chapters')
    config.add_route('professor-drive','/professor-drive')
    config.add_route('admin-syllabus','/admin-syllabus')
    config.add_route('professor-create','/professor-create')
    config.add_route('professor-questions','/professor-questions')
    config.add_route('professor-update','/professor-update')
    config.add_route('student-chapters','/student-chapters')
    config.add_route('student-questions','/student-questions')
    config.add_route('index-sign','/index-sign')
    config.add_route('admin-create','/admin-create')
    config.add_route('saveprofdata','/saveprofdata')
    config.add_route('savestuddata','/savestuddata')
    config.add_route('create_qp','/create_qp')
    config.add_route('admin-link-query','/admin-link-query')
    config.add_route('save-workspace','/save-workspace')
    config.add_route('admin-link-save','/admin-link-save')
    config.add_route('savesyldata','/savesyldata')
    config.add_route('updatedata','/updatedata')
    config.add_route('logout','/logout')
    config.add_route('opentest','/opentest')
    config.add_route('downloadtest','/downloadtest')
    config.add_route('forgotpassword','/forgotpassword')
    config.add_route('uploadstu','/uploadstu')
    config.add_route('admin-students-json','/admin-students-json')
    config.add_route('jex','/jex') 

